name: Split Packages

on:
  push:
    branches:
      - main
    tags:
      - 'cloud/[0-9]*'
      - 'cloud-ops/[0-9]*'
      - 'cloud-composer/[0-9]*'
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: craftcms/.github/.github/workflows/code-quality.yml@v3
    with:
      node_version: '18'
      php_version: '8.3'
      jobs: '["ecs", "phpstan", "prettier"]'

  split:
    needs: ci
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: cloud-plugin
            path: packages/cloud
            prefix: cloud/
          - name: cloud-composer
            path: packages/cloud-composer
            prefix: cloud-composer/
          - name: cloud-ops
            path: packages/cloud-ops
            prefix: cloud-ops/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG="${{ github.ref_name }}"
            PREFIX="${{ matrix.package.prefix }}"
            if [[ "$TAG" == ${PREFIX}* ]]; then
              echo "tag=${TAG#$PREFIX}" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Split ${{ matrix.package.name }}
        uses: danharrin/monorepo-split-github-action@v2.4.4
        with:
          package_directory: ${{ matrix.package.path }}
          repository_organization: craftcms
          repository_name: ${{ matrix.package.name }}
          user_name: 'craftcms'
          user_email: 'github@craftcms.com'
          tag: ${{ steps.tag.outputs.tag }}
          branch: ${{ matrix.package.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.CLOUD_SPLIT_REPO_TOKEN }}
